### ISSUE TITLE
Package not found in PyPI

### ISSUE THREAD

**Issue by raiyankamal** [Brightspace/valence-sdk-python#12]
As of today, this package is not available on PyPI. The URL given in docs lead to a 404 error page. Attempting to install through pip also fails.

https://pypi.org/project/D2LValence/

**Comment by brettdw-tamu** [comment]
I've noticed the same thing today as well. I'm currently copying the installed package directories from one virtual environment into the site-packages directory of new virtual environments in order to keep using it.

As a side note: even though the last published version of the package was 1.2.2, which was only tested up to Python 3.5, it works just fine with my current environments running 3.10.13. I'm not sure why this package was unpublished.

**Comment by rbistolfi** [comment]
This is affecting us as well

**Comment by ViktorHaag** [comment]
Thanks for the issue. The package published in PyPi was never really officially supported and hadn't been maintained for several years. It has been removed. We do have long-range plans to improve enablement materials around the Brightspace APIs, but no immediate plans to provide similar utility libraries. I will amend the documentation here not to refer to this package any longer.

(edit -- addressed with https://github.com/Brightspace/valence-sdk-python/pull/13)

**Comment by djredhand** [comment]
Thanks for ripping it out of PyPi!
