### ISSUE TITLE
d2lvalence_util repo?

### ISSUE THREAD

**Issue by midnightlynx** [Brightspace/valence-sdk-python#5]
The `data` and `service` submodules were spun off from this package to their own `d2lvalence_util` package.

That package is on pypi, but the repo doesn't seem to have made it to github. There are a few bugs that need fixing, and it needs python 2.7 support to match this project.

If Brightspace could add that project to their github, that'd be great.

**Comment by ViktorHaag** [comment]
The utility package may, at some point, be entirely removed from PyPi, and won't be put here on GitHub in its current form.

**Comment by midnightlynx** [comment]
Okay.
Are there plans to release something before then of a different form, but equivalent function?
Or do we need to start building our own?

**Comment by ViktorHaag** [comment]
Sorry, there are no current plans to release something of a different form, but equivalent function. The existing package is still sitting on PyPi largely because of that: there are no current plans to maintain it, or replace it.

I think that this fully answers the original request (and sorry that it's not more positive news), so I'm going to close this.
